### ISSUE TITLE
Create an API to fetch all teams

### ISSUE THREAD

**Issue by rannieo** [einnar82/mpl-ph-api#2]
Get all participating teams in MPL PH via https://ph-mpl.com/en/data in form of web scraping :)

**Comment by shin-iji** [comment]
@einnar82  can assign this to me?

**Comment by rannieo** [comment]
Hello @shin-iji ,

Yes you can, please read the updated instruction.

Thanks.

**Comment by yash-93** [comment]
@einnar82 I opened a PR for the task.

**Comment by rannieo** [comment]
Hello @yash-93 

I already merged the changes. Please check the PR number #12  Thank you!
