### ISSUE TITLE
Create an API to fetch players statistics

### ISSUE THREAD

**Issue by rannieo** [einnar82/mpl-ph-api#3]
Get all players stats via https://ph-mpl.com/en/data in form of web scraping :)

**Comment by yerlantemir** [comment]
Hi, could you give detailed explanation ? Should it be exreacted from here  https://ph-mpl.com/en/data ?

**Comment by rannieo** [comment]
Yes @yerlantemir , data must be extracted at the given link.

**Comment by yerlantemir** [comment]
Okay, assign it to me @einnar82

**Comment by rannieo** [comment]
Okay @yerlantemir thanks

**Comment by rannieo** [comment]
Hello guys,

I update the issue description.

Thanks :)

**Comment by yerlantemir** [comment]
done @einnar82

**Comment by rannieo** [comment]
Thank you @yerlantemir ! :) I will close the issue.
