### ISSUE TITLE
Create an API for Hero Statistics

### ISSUE THREAD

**Issue by rannieo** [einnar82/mpl-ph-api#4]
Fetch all hero statistic for MPL via https://ph-mpl.com/en/data in form of web scraping :)

**Comment by sauravsolanki** [comment]
@einnar82 Please assign me this.

**Comment by rannieo** [comment]
Yes, @sauravsolanki just visit this [link](https://ph-mpl.com/en/data) and visit hero statistics. 😉

**Comment by mukundchoudhary28** [comment]
Hey @einnar82 what's the format in which you want your output data to be?

**Comment by rannieo** [comment]
Hello guys, 

I update the issue description. 

Thanks :)

**Comment by rannieo** [comment]
Hello @mukundch28 ,

The data format must be in form of JSON. You may customize the json fields of it, :)

**Comment by jabo-bernardo** [comment]
I would like to work on this.
