### ISSUE TITLE
add MVP structure!

### ISSUE THREAD

**Issue by sauravsolanki** [einnar82/mpl-ph-api#8]
Dear Author  @einnar82 ,
Currently code is at the initial phase, so I would like to add soemthing to it:
1.  Typescript
2. MVP code structure.
3. Validation Package like DTO, etc. 

Please let me know your view and assign me accordingly.

**Comment by rannieo** [comment]
Hello, @sauravsolanki ,

That's nice, but i intend it make it simple as possible, since this API is more on web scraping from a specific website. :)
